### ISSUE TITLE
last_poll : NoMethodError: undefined method `fetch' for nil:NilClass

### ISSUE THREAD

**Issue by bricesanchez** [nebulab/cangaroo#28]
Hello,

I've pull the master branch @ 76a6b29  and now i've this error when i try to run my first `PollJob`

It comes from this : https://github.com/nebulab/cangaroo/blob/master/app/jobs/cangaroo/poll_job.rb#L16

Do i need to configure something for `last_poll` ?

```ruby
➜  acc-001-api git:(master) ✗ rake cangaroo:poll
Running via Spring preloader in process 13543
rake aborted!
NoMethodError: undefined method `fetch' for nil:NilClass
/Users/bci20/Sites/bisscomm/cangaroo/app/jobs/cangaroo/poll_job.rb:16:in `perform'
/Users/bci20/Sites/acc-001-api/.gems/gems/activejob-4.2.6/lib/active_job/execution.rb:32:in `block in perform_now'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:117:in `call'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/Users/bci20/Sites/acc-001-api/.gems/gems/activejob-4.2.6/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:441:in `instance_exec'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:342:in `block in simple'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:497:in `block in around'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/Users/bci20/Sites/acc-001-api/.gems/gems/activejob-4.2.6/lib/active_job/logging.rb:23:in `block (4 levels) in <module:Logging>'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `block in instrument'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `instrument'
/Users/bci20/Sites/acc-001-api/.gems/gems/activejob-4.2.6/lib/active_job/logging.rb:22:in `block (3 levels) in <module:Logging>'
/Users/bci20/Sites/acc-001-api/.gems/gems/activejob-4.2.6/lib/active_job/logging.rb:43:in `block in tag_logger'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:26:in `tagged'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `tagged'
/Users/bci20/Sites/acc-001-api/.gems/gems/activejob-4.2.6/lib/active_job/logging.rb:43:in `tag_logger'
/Users/bci20/Sites/acc-001-api/.gems/gems/activejob-4.2.6/lib/active_job/logging.rb:19:in `block (2 levels) in <module:Logging>'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:441:in `instance_exec'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:342:in `block in simple'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:497:in `block in around'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_perform_callbacks'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/bci20/Sites/acc-001-api/.gems/gems/activejob-4.2.6/lib/active_job/execution.rb:31:in `perform_now'
/Users/bci20/Sites/acc-001-api/.gems/gems/activejob-4.2.6/lib/active_job/execution.rb:21:in `execute'
/Users/bci20/Sites/acc-001-api/.gems/gems/activejob-4.2.6/lib/active_job/queue_adapters/inline_adapter.rb:14:in `enqueue'
/Users/bci20/Sites/acc-001-api/.gems/gems/activejob-4.2.6/lib/active_job/enqueuing.rb:71:in `block in enqueue'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:117:in `call'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/Users/bci20/Sites/acc-001-api/.gems/gems/activejob-4.2.6/lib/active_job/logging.rb:14:in `block (3 levels) in <module:Logging>'
/Users/bci20/Sites/acc-001-api/.gems/gems/activejob-4.2.6/lib/active_job/logging.rb:43:in `block in tag_logger'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:26:in `tagged'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `tagged'
/Users/bci20/Sites/acc-001-api/.gems/gems/activejob-4.2.6/lib/active_job/logging.rb:43:in `tag_logger'
/Users/bci20/Sites/acc-001-api/.gems/gems/activejob-4.2.6/lib/active_job/logging.rb:13:in `block (2 levels) in <module:Logging>'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:441:in `instance_exec'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:342:in `block in simple'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:497:in `block in around'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_enqueue_callbacks'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
/Users/bci20/Sites/acc-001-api/.gems/gems/activejob-4.2.6/lib/active_job/enqueuing.rb:67:in `enqueue'
/Users/bci20/Sites/bisscomm/cangaroo/app/interactors/cangaroo/run_polls.rb:7:in `block in call'
/Users/bci20/Sites/bisscomm/cangaroo/app/interactors/cangaroo/run_polls.rb:6:in `each'
/Users/bci20/Sites/bisscomm/cangaroo/app/interactors/cangaroo/run_polls.rb:6:in `call'
/Users/bci20/Sites/acc-001-api/.gems/gems/interactor-3.1.0/lib/interactor.rb:143:in `block in run!'
/Users/bci20/Sites/acc-001-api/.gems/gems/interactor-3.1.0/lib/interactor/hooks.rb:213:in `block in with_hooks'
/Users/bci20/Sites/acc-001-api/.gems/gems/interactor-3.1.0/lib/interactor/hooks.rb:224:in `run_around_hooks'
/Users/bci20/Sites/acc-001-api/.gems/gems/interactor-3.1.0/lib/interactor/hooks.rb:211:in `with_hooks'
/Users/bci20/Sites/acc-001-api/.gems/gems/interactor-3.1.0/lib/interactor.rb:142:in `run!'
/Users/bci20/Sites/acc-001-api/.gems/gems/interactor-3.1.0/lib/interactor.rb:115:in `run'
/Users/bci20/Sites/acc-001-api/.gems/gems/interactor-3.1.0/lib/interactor.rb:50:in `tap'
/Users/bci20/Sites/acc-001-api/.gems/gems/interactor-3.1.0/lib/interactor.rb:50:in `call'
/Users/bci20/Sites/bisscomm/cangaroo/lib/tasks/cangaroo_tasks.rake:3:in `block (2 levels) in <top (required)>'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/bci20/Sites/acc-001-api/.gems/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
-e:1:in `<main>'
Tasks: TOP => cangaroo:poll
(See full trace by running task with --trace)
```

**Comment by iloveitaly** [comment]
What does your polljob look like?

- Mike <http://mikebian.co/>

**Comment by bricesanchez** [comment]
```ruby
module Cangaroo
  class ProductPollJob < Cangaroo::PollJob
    connection 'chaindrive'
    frequency 5.minutes
    path '/get_products'
    parameters(
      product_filters: {
        item: 'PRODUCTID=270097'
      }
    )
  end
end
```

**Comment by iloveitaly** [comment]
@bricesanchez actually, I think PollJob on master might be broken. I changed the logic in my customization branch and I don't think all of the changes made it into master properly. I'll try to take a look this upcoming week and clean things up.

**Comment by bricesanchez** [comment]
Thanks, I've temporary set `last_poll  = 0` to perform `PollJob`

**Comment by iloveitaly** [comment]
@bricesanchez great, I'm glad that worked. Checkout this branch if you need additional help: https://github.com/iloveitaly/cangaroo/tree/customized

**Comment by bricesanchez** [comment]
Me too but i had to merge #23 in my PR to be able to use my integration : https://github.com/nebulab/cangaroo/compare/master...bisscomm:acc-001

**Comment by AlessioRocco** [comment]
@iloveitaly do you have news about this, can you make a new PR with your fixes.

**Comment by iloveitaly** [comment]
Haven't had a chance yet, I'll try my best to queue up a couple of other
PRs this week.

**Comment by bricesanchez** [comment]
:up :)
